import GlobalContext from '@/context/app'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Basic Profile Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <GlobalContext>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <div id='modal'></div>
          <div id='toast'></div>
        </body>
      </html>
    </GlobalContext>

  )
}
